version: '3.8'

services:
  db:
    image: postgres:16
    container_name: endeavor-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: endeavor_db
      POSTGRES_USER: endeavor_user
      POSTGRES_PASSWORD: endeavor_pass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
